### ISSUE TITLE
192.168.4.1/admin doesn't work

### ISSUE THREAD

**Issue by cl1y** [M1z23R/ESP8266-EvilTwin#18]
after selecting a target and starting evil twin it spawns a wifi with the same ssid as the targets. when i connect to that ssid and go to the address 192.168.4.1/admin it redirects to the captive portal page. also pls release the v2 .bin file

**Comment by M1z23R** [comment]
Two cases:
First one: EwilTwin isn't active
192.168.4.1 and 192.168.4.1/admin are the same
2nd case: EwilTwin IS active
192.168.4.1 will display fake login page 
192.168.4.1/admin will display admin panel.

I'll add .bin in the releases later today.

**Comment by cl1y** [comment]
I'll try v2 when you release the bin file. i think that was a bug that didn't let me open the admin panel (on the 2nd case). thank you for this awesome project.
